"""
Appendix Writer.

Generates the appendix section of the
attack surface assessment report.
"""

from datetime import datetime


class AppendixWriter:
    """
    Generates the appendix section.
    """

    def __init__(self):
        """
        Initialize the appendix writer.
        """

        pass

    def write(
        self,
        normalized_data: dict,
    ) -> str:
        """
        Generate the appendix section.

        Parameters
        ----------
        normalized_data : dict
            Normalized reconnaissance data.

        Returns
        -------
        str
            Rendered markdown section.
        """

        dns = normalized_data.get(
            "dns",
            {},
        )

        hostname = dns.get(
            "hostname",
            "Unknown",
        )

        timestamp = (
            datetime.utcnow()
            .isoformat(timespec="seconds")
            + "Z"
        )

        appendix = f"""# Appendix

## Assessment Metadata

| Field | Value |
|-------|-------|
| Target | {hostname} |
| Assessment Date | {timestamp} |
| Assessment Type | External Attack Surface Reconnaissance |
| Engine | Recon Engine |
| Report Version | 1.0.0 |

---

## Methodology

The assessment followed a structured reconnaissance
workflow consisting of:

1. DNS Enumeration
2. HTTP/HTTPS Reachability Testing
3. Network Service Enumeration
4. TLS Inspection
5. Virtual Host Enumeration
6. Technology Fingerprinting
7. Data Normalization
8. Evidence Generation
9. Report Generation

The assessment was limited to publicly accessible
information and did not perform exploitation,
credential attacks, or destructive testing.

---

## Reconnaissance Tools

The following tools were used during the assessment:

- dig
- curl
- nmap
- OpenSSL
- Virtual Host Enumerator
- Technology Fingerprinting Engine

---

## Evidence Produced

The following evidence artifacts were generated
during the assessment:

- normalized.json
- scope-register.csv
- request-ledger.csv
- evidence-index.csv
- assessment-manifest.json
- continuity-record.md
- integrity-attestation.md
- manifest.sha256

---

## Evidence Integrity

Evidence integrity is maintained through
SHA-256 hashes recorded within
`manifest.sha256`.

The integrity attestation provides
verification guidance for validating all
generated artifacts.

---

## Assessment Limitations

This assessment reflects the externally
observable attack surface at the time the
reconnaissance was performed.

Infrastructure, DNS records, exposed services,
certificates, and technologies may change over
time.

The report should therefore be considered a
snapshot of the target environment.

---

## End of Report

This concludes the automated attack surface
assessment generated by the Recon Engine.
"""

        return appendix


def main() -> None:
    """
    Execute the appendix writer independently.
    """

    sample = {
        "dns": {
            "hostname": "example.com",
        }
    }

    writer = AppendixWriter()

    print(
        writer.write(sample)
    )


if __name__ == "__main__":
    main()