"""
Integrity Writer.

Writes the integrity attestation.
"""

from pathlib import Path
from datetime import UTC, datetime


class IntegrityWriter:
    """
    Writes the integrity attestation.
    """

    def __init__(self):
        self._output_directory = Path("output")

        self._output_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

    def write(self, normalized_data: dict) -> dict:
        """
        Write the integrity attestation.
        """

        output_file = (
            self._output_directory /
            "integrity-attestation.md"
        )

        dns = normalized_data.get("dns", {})

        target = dns.get(
            "hostname",
            "unknown"
        )

        generated = (
            datetime.now(UTC)
            .isoformat(timespec="seconds")
            .replace("+00:00", "Z")
        )

        candidate = "Alex Mulinge"

        content = f"""# Integrity Attestation

## Assessment

| Field | Value |
|-------|-------|
| Target | {target} |
| Generated | {generated} |
| Status | Complete |

---

## Integrity Statement

I attest that this submission represents the evidence
generated by the Recon Engine during the assessment.

The submitted artifacts have not been intentionally
modified after generation except for documented
submission preparation.

Artifact integrity may be verified using the
accompanying **manifest.sha256** file.

---

## Evidence Included

- normalized.json
- scope-register.csv
- request-ledger.csv
- evidence-index.csv
- assessment-manifest.json
- continuity-record.md
- integrity-attestation.md
- foothold-evidence.txt
- attack-surface-report.pdf
- raw-output/

---

## Verification Procedure

1. Open `manifest.sha256`.
2. Compute the SHA-256 hash of every listed artifact.
3. Compare each computed hash with the recorded value.
4. Matching hashes confirm artifact integrity.

---

## Candidate Declaration

I declare that:

- this submission represents my own work;
- assistance used during development has been acknowledged where applicable;
- I accept responsibility for the submitted implementation and evidence.

---

## Signature

Candidate:

{candidate}

Date:

{generated[:10]}
"""

        with output_file.open(
            mode="w",
            encoding="utf-8",
        ) as file:
            file.write(content)

        return {
            "success": True,
            "artifact": "integrity-attestation",
            "path": str(output_file),
        }


def main() -> None:
    sample = {
        "dns": {
            "hostname": "example.com"
        }
    }

    writer = IntegrityWriter()

    print(writer.write(sample))


if __name__ == "__main__":
    main()